### ISSUE TITLE
github-enterprise-url param missing from scanGithubEnterprise.go

### ISSUE THREAD

**Issue by funkwhatyouheard** [N0MoreSecr3ts/wraith#100]
Think the ability to set that param needs to be in there. Looked like the reference to the param is still in session.go. Need to be able to point at a specific github instance for hosted solutions.

**Comment by funkwhatyouheard** [comment]
Addressed this and a couple other issues in https://github.com/N0MoreSecr3ts/wraith/pull/101

**Comment by mattyjones** [comment]
@funkwhatyouheard fixed in develop
