### ISSUE TITLE
New Github token will fail the regex match

### ISSUE THREAD

**Issue by Shashank-In** [N0MoreSecr3ts/wraith#103]
Github has a different GitHub token pattern now and starts with  `ghp_`

Hence the below regex match will fail. 

https://github.com/N0MoreSecr3ts/wraith/blob/master/core/github.go#L155-L160

I have added a pull request for the fix:
https://github.com/N0MoreSecr3ts/wraith/pull/104

**Comment by mattyjones** [comment]
@Shashank-In I am working through this now in the PR, you can check the status and follow along there. Thanks again for this!
