### ISSUE TITLE
Codecov Security Update

### ISSUE THREAD

**Issue by codeEmitter** [N0MoreSecr3ts/wraith#105]
There is a [security alert from Codecov](https://about.codecov.io/security-update/) which is used in the .travis-ci.yml file here:  https://github.com/N0MoreSecr3ts/wraith/blob/master/.travis.yml#L17.  Their recommendation:

> We strongly recommend affected users immediately re-roll all of their credentials, tokens, or keys located in the environment variables in their CI processes that used one of Codecov’s Bash Uploaders.

I noticed this file, unused as a result of a bad merge on my part, in [our fork of gitrob](https://gitlab.com/gitlab-com/gl-security/security-operations/gl-redteam/gitrob) and removed it and wanted to give you a heads up.

**Comment by mattyjones** [comment]
@codeEmitter Thanks for the heads up!
