### ISSUE TITLE
Version of Release .0.0.8 Still Prints as .0.0.7

### ISSUE THREAD

**Issue by JierdanEntreri** [N0MoreSecr3ts/wraith#106]
This is obviously a minute issue but it could cause confusion for users if they are trying to troubleshoot their build against release.  Changing a single character in version.go fixes this. Figured I'd bring this up. This is true for both the zip and tar installations.

**Comment by mattyjones** [comment]
Thanks, I will update this.

**Comment by mattyjones** [comment]
@JierdanEntreri  fixed, thank for pointing this out.
