### ISSUE TITLE
Error while "make build"

### ISSUE THREAD

**Issue by AnkitCuriosity** [N0MoreSecr3ts/wraith#109]
Hello team,

I'm operating over Ubuntu 16.04 LTS.

This how my GO environemtal variables are configured -:

![1](https://user-images.githubusercontent.com/58471667/117581076-9742c900-b118-11eb-87a0-e2473a72af7e.png)

Whenever I run "make build" command I get this error -:

toor@ubuntu:~$ cd /usr/lib/go
toor@ubuntu:/usr/lib/go$ cd src
toor@ubuntu:/usr/lib/go/src$ cd wraith
toor@ubuntu:/usr/lib/go/src/wraith$ make build
/usr/lib/go-1.6/src/wraith/core/git.go:5:2: cannot find package "context" in any of:
	/usr/lib/go-1.6/src/vendor/context (vendor tree)
	/usr/lib/go/src/vendor/context
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/usr/lib/go/src/context (from $GOPATH)
/usr/lib/go-1.6/src/wraith/core/bindata.go:32:2: cannot find package "github.com/elazarl/go-bindata-assetfs" in any of:
	/usr/lib/go-1.6/src/vendor/github.com/elazarl/go-bindata-assetfs (vendor tree)
	/usr/lib/go/src/vendor/github.com/elazarl/go-bindata-assetfs
	/usr/lib/go-1.6/src/github.com/elazarl/go-bindata-assetfs (from $GOROOT)
	/usr/lib/go/src/github.com/elazarl/go-bindata-assetfs (from $GOPATH)
/usr/lib/go-1.6/src/wraith/core/log.go:8:2: cannot find package "github.com/fatih/color" in any of:
	/usr/lib/go-1.6/src/vendor/github.com/fatih/color (vendor tree)
	/usr/lib/go/src/vendor/github.com/fatih/color
	/usr/lib/go-1.6/src/github.com/fatih/color (from $GOROOT)
	/usr/lib/go/src/github.com/fatih/color (from $GOPATH)
/usr/lib/go-1.6/src/wraith/core/router.go:10:2: cannot find package "github.com/gin-contrib/secure" in any of:
	/usr/lib/go-1.6/src/vendor/github.com/gin-contrib/secure (vendor tree)
	/usr/lib/go/src/vendor/github.com/gin-contrib/secure
	/usr/lib/go-1.6/src/github.com/gin-contrib/secure (from $GOROOT)
	/usr/lib/go/src/github.com/gin-contrib/secure (from $GOPATH)
/usr/lib/go-1.6/src/wraith/core/router.go:11:2: cannot find package "github.com/gin-contrib/static" in any of:
	/usr/lib/go-1.6/src/vendor/github.com/gin-contrib/static (vendor tree)
	/usr/lib/go/src/vendor/github.com/gin-contrib/static
	/usr/lib/go-1.6/src/github.com/gin-contrib/static (from $GOROOT)
	/usr/lib/go/src/github.com/gin-contrib/static (from $GOPATH)
/usr/lib/go-1.6/src/wraith/core/router.go:12:2: cannot find package "github.com/gin-gonic/gin" in any of:
	/usr/lib/go-1.6/src/vendor/github.com/gin-gonic/gin (vendor tree)
	/usr/lib/go/src/vendor/github.com/gin-gonic/gin
	/usr/lib/go-1.6/src/github.com/gin-gonic/gin (from $GOROOT)
	/usr/lib/go/src/github.com/gin-gonic/gin (from $GOPATH)
/usr/lib/go-1.6/src/wraith/core/git.go:8:2: cannot find package "github.com/google/go-github/github" in any of:
	/usr/lib/go-1.6/src/vendor/github.com/google/go-github/github (vendor tree)
	/usr/lib/go/src/vendor/github.com/google/go-github/github
	/usr/lib/go-1.6/src/github.com/google/go-github/github (from $GOROOT)
	/usr/lib/go/src/github.com/google/go-github/github (from $GOPATH)
/usr/lib/go-1.6/src/wraith/core/io.go:4:2: cannot find package "github.com/mitchellh/go-homedir" in any of:
	/usr/lib/go-1.6/src/vendor/github.com/mitchellh/go-homedir (vendor tree)
	/usr/lib/go/src/vendor/github.com/mitchellh/go-homedir
	/usr/lib/go-1.6/src/github.com/mitchellh/go-homedir (from $GOROOT)
	/usr/lib/go/src/github.com/mitchellh/go-homedir (from $GOPATH)
/usr/lib/go-1.6/src/wraith/cmd/updateRules.go:10:2: cannot find package "github.com/otiai10/copy" in any of:
	/usr/lib/go-1.6/src/vendor/github.com/otiai10/copy (vendor tree)
	/usr/lib/go/src/vendor/github.com/otiai10/copy
	/usr/lib/go-1.6/src/github.com/otiai10/copy (from $GOROOT)
	/usr/lib/go/src/github.com/otiai10/copy (from $GOPATH)
/usr/lib/go-1.6/src/wraith/cmd/root.go:7:2: cannot find package "github.com/spf13/cobra" in any of:
	/usr/lib/go-1.6/src/vendor/github.com/spf13/cobra (vendor tree)
	/usr/lib/go/src/vendor/github.com/spf13/cobra
	/usr/lib/go-1.6/src/github.com/spf13/cobra (from $GOROOT)
	/usr/lib/go/src/github.com/spf13/cobra (from $GOPATH)
/usr/lib/go-1.6/src/wraith/cmd/root.go:8:2: cannot find package "github.com/spf13/viper" in any of:
	/usr/lib/go-1.6/src/vendor/github.com/spf13/viper (vendor tree)
	/usr/lib/go/src/vendor/github.com/spf13/viper
	/usr/lib/go-1.6/src/github.com/spf13/viper (from $GOROOT)
	/usr/lib/go/src/github.com/spf13/viper (from $GOPATH)
/usr/lib/go-1.6/src/wraith/cmd/updateRules.go:12:2: cannot find package "github.com/whilp/git-urls" in any of:
	/usr/lib/go-1.6/src/vendor/github.com/whilp/git-urls (vendor tree)
	/usr/lib/go/src/vendor/github.com/whilp/git-urls
	/usr/lib/go-1.6/src/github.com/whilp/git-urls (from $GOROOT)
	/usr/lib/go/src/github.com/whilp/git-urls (from $GOPATH)
/usr/lib/go-1.6/src/wraith/core/gitlab.go:9:2: cannot find package "github.com/xanzy/go-gitlab" in any of:
	/usr/lib/go-1.6/src/vendor/github.com/xanzy/go-gitlab (vendor tree)
	/usr/lib/go/src/vendor/github.com/xanzy/go-gitlab
	/usr/lib/go-1.6/src/github.com/xanzy/go-gitlab (from $GOROOT)
	/usr/lib/go/src/github.com/xanzy/go-gitlab (from $GOPATH)
/usr/lib/go-1.6/src/wraith/core/git.go:9:2: cannot find package "golang.org/x/oauth2" in any of:
	/usr/lib/go-1.6/src/vendor/golang.org/x/oauth2 (vendor tree)
	/usr/lib/go/src/vendor/golang.org/x/oauth2
	/usr/lib/go-1.6/src/golang.org/x/oauth2 (from $GOROOT)
	/usr/lib/go/src/golang.org/x/oauth2 (from $GOPATH)
/usr/lib/go-1.6/src/wraith/core/localPath.go:13:2: cannot find package "golang.org/x/sync/errgroup" in any of:
	/usr/lib/go-1.6/src/vendor/golang.org/x/sync/errgroup (vendor tree)
	/usr/lib/go/src/vendor/golang.org/x/sync/errgroup
	/usr/lib/go-1.6/src/golang.org/x/sync/errgroup (from $GOROOT)
	/usr/lib/go/src/golang.org/x/sync/errgroup (from $GOPATH)
/usr/lib/go-1.6/src/wraith/cmd/updateRules.go:13:2: cannot find package "gopkg.in/src-d/go-git.v4" in any of:
	/usr/lib/go-1.6/src/vendor/gopkg.in/src-d/go-git.v4 (vendor tree)
	/usr/lib/go/src/vendor/gopkg.in/src-d/go-git.v4
	/usr/lib/go-1.6/src/gopkg.in/src-d/go-git.v4 (from $GOROOT)
	/usr/lib/go/src/gopkg.in/src-d/go-git.v4 (from $GOPATH)
/usr/lib/go-1.6/src/wraith/cmd/updateRules.go:14:2: cannot find package "gopkg.in/src-d/go-git.v4/plumbing" in any of:
	/usr/lib/go-1.6/src/vendor/gopkg.in/src-d/go-git.v4/plumbing (vendor tree)
	/usr/lib/go/src/vendor/gopkg.in/src-d/go-git.v4/plumbing
	/usr/lib/go-1.6/src/gopkg.in/src-d/go-git.v4/plumbing (from $GOROOT)
	/usr/lib/go/src/gopkg.in/src-d/go-git.v4/plumbing (from $GOPATH)
/usr/lib/go-1.6/src/wraith/core/git.go:12:2: cannot find package "gopkg.in/src-d/go-git.v4/plumbing/object" in any of:
	/usr/lib/go-1.6/src/vendor/gopkg.in/src-d/go-git.v4/plumbing/object (vendor tree)
	/usr/lib/go/src/vendor/gopkg.in/src-d/go-git.v4/plumbing/object
	/usr/lib/go-1.6/src/gopkg.in/src-d/go-git.v4/plumbing/object (from $GOROOT)
	/usr/lib/go/src/gopkg.in/src-d/go-git.v4/plumbing/object (from $GOPATH)
/usr/lib/go-1.6/src/wraith/core/github.go:11:2: cannot find package "gopkg.in/src-d/go-git.v4/plumbing/transport/http" in any of:
	/usr/lib/go-1.6/src/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/http (vendor tree)
	/usr/lib/go/src/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/http
	/usr/lib/go-1.6/src/gopkg.in/src-d/go-git.v4/plumbing/transport/http (from $GOROOT)
	/usr/lib/go/src/gopkg.in/src-d/go-git.v4/plumbing/transport/http (from $GOPATH)
/usr/lib/go-1.6/src/wraith/core/github.go:12:2: cannot find package "gopkg.in/src-d/go-git.v4/storage/memory" in any of:
	/usr/lib/go-1.6/src/vendor/gopkg.in/src-d/go-git.v4/storage/memory (vendor tree)
	/usr/lib/go/src/vendor/gopkg.in/src-d/go-git.v4/storage/memory
	/usr/lib/go-1.6/src/gopkg.in/src-d/go-git.v4/storage/memory (from $GOROOT)
	/usr/lib/go/src/gopkg.in/src-d/go-git.v4/storage/memory (from $GOPATH)
/usr/lib/go-1.6/src/wraith/core/git.go:13:2: cannot find package "gopkg.in/src-d/go-git.v4/utils/merkletrie" in any of:
	/usr/lib/go-1.6/src/vendor/gopkg.in/src-d/go-git.v4/utils/merkletrie (vendor tree)
	/usr/lib/go/src/vendor/gopkg.in/src-d/go-git.v4/utils/merkletrie
	/usr/lib/go-1.6/src/gopkg.in/src-d/go-git.v4/utils/merkletrie (from $GOROOT)
	/usr/lib/go/src/gopkg.in/src-d/go-git.v4/utils/merkletrie (from $GOPATH)
/usr/lib/go-1.6/src/wraith/core/signatures.go:6:2: cannot find package "gopkg.in/yaml.v2" in any of:
	/usr/lib/go-1.6/src/vendor/gopkg.in/yaml.v2 (vendor tree)
	/usr/lib/go/src/vendor/gopkg.in/yaml.v2
	/usr/lib/go-1.6/src/gopkg.in/yaml.v2 (from $GOROOT)
	/usr/lib/go/src/gopkg.in/yaml.v2 (from $GOPATH)
Makefile:68: recipe for target 'prep' failed
make: *** [prep] Error 1

**Comment by mattyjones** [comment]
@AnkitCuriosity This may be due to you $GOPATH. Why is it there and not somewhere like $HOME/go which I believe is the standard?

How did you install Go (apt, download, etc)?
Did you make any changes to it after install?

The error is due to missing libraries and not being able to pull them in. Look at the `make build` command, it depends on a bunch of others, start at the beginning, fairly certain the prep one will fail.

You could always try `go get` on the packages it can't find, and/or try `go build` without using the makefile, the makefile just allows an easier way to manage the cross-platform building and testing of packages before they are built. You can simply copypasta the commands directly into the command line. I use the makefile on both OSX and Ubuntu and some other flavors.

Let me know the output from the above commands and thoughts if you want.

**Comment by AnkitCuriosity** [comment]
Hello @mattyjones

I used apt for installation and for some reason $GOPATH & $GOROOT pointed to wrong directories. But anyways I sorted this out by completely removing and re-installing the go.

But now I've ran into a new problem. Now when I run "make build" or "go build" then it throws this error -:

toor@ubuntu:~$ cd /usr/local/go/src/wraith
toor@ubuntu:/usr/local/go/src/wraith$ make build
go get wraith: copying /tmp/go-build84712651/b001/exe/a.out: open /usr/local/go/bin/wraith: permission denied
Makefile:68: recipe for target 'prep' failed
make: *** [prep] Error 1
toor@ubuntu:/usr/local/go/src/wraith$ go build
go build wraith: copying /tmp/go-build4062983931/b001/exe/a.out: open wraith: permission denied
toor@ubuntu:/usr/local/go/src/wraith$ 

Any workaround this ?

**Comment by mattyjones** [comment]
You don't have the paths right possibly still or you need to just reset your GOROOT. This is happening because you don't have write permission to that dir and your OS is telling go to put files there as it believes it is where the go stuff is.

Post the values of $GOPATH and $GOROOT

I have a ubuntu 20 box I will poke at.

**Comment by AnkitCuriosity** [comment]
These are my values -:

![Screenshot from 2021-05-18 11-56-37](https://user-images.githubusercontent.com/58471667/118602594-85c08780-b7d0-11eb-9289-586e77294cf3.png)

**Comment by circleous** [comment]
> /usr/lib/go-1.6/src/wraith/core/git.go:5:2: cannot find package "context" in any of:

package `context` is introduced in go version 1.7, but it seems like you're still using 1.6. So, either update your go version to 1.7 or just use latest (https://golang.org/dl/)
