### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by sabeesh03** [N0MoreSecr3ts/wraith#11]
go get github.com/mattyjones/gitrob
go: downloading google.golang.org/appengine v1.0.0
# github.com/michenriksen/gitrob/core
../Desktop/GO/pkg/mod/github.com/michenriksen/gitrob@v2.0.0-beta+incompatible/core/github.go:43:5: cannot use user.ID (type *int64) as type *int in field value
../Desktop/GO/pkg/mod/github.com/michenriksen/gitrob@v2.0.0-beta+incompatible/core/github.go:73:11: cannot use repo.ID (type *int64) as type *int in field value
../Desktop/GO/pkg/mod/github.com/michenriksen/gitrob@v2.0.0-beta+incompatible/core/github.go:105:73: cannot use member.ID (type *int64) as type *int in field value
getting error during installation

**Comment by mattyjones** [comment]
@sabeesh03 This has been fixed with the latest master. The issue was that is was still pulling from the original project and the new pull requests I merged in broke the original code. All should be light and bright now.

**Comment by sabeesh03** [comment]
So matt should I delete the repo and redownload it

**Comment by mattyjones** [comment]
If it is this repo then you can just `git pull origin master` or sure you can delete the repo and just do a new `git clone <repo>`

**Comment by sabeesh03** [comment]
Desktop/GO/src/github.com/michenriksen/gitrob/core/router.go:41:54: too few values in assetfs.AssetFS literal

did a new repo
same issue

**Comment by mattyjones** [comment]
@sabeesh03 ok I will look into it. I am fairly certain it has to do with the build process and how you are doing it. This is laid out a little different than most projects so wired errors keep popping up. One of the first thing I am going to fix is a little cleaner if a layout.

**Comment by mattyjones** [comment]
@sabeesh03 I can't replicate on my OSX or Kali box when I build from master. I can replicate it in the CircleCi build. I have no idea yet what the difference it. I have tried pulling the lastest, I am running the same version locally as the build and I tested using the same commands. This has me stumped for the moment.
