### ISSUE TITLE
no issues detected (no files scanned) in wraith-test (plus issues when updating signatures)

### ISSUE THREAD

**Issue by javixeneize** [N0MoreSecr3ts/wraith#110]
Hi

I have configured the tool to run it against the wraith-test repo and it doesnt seem to scan anything

wraith v0.0.7 started at 2021-05-13T11:49:43+01:00
Loaded 61 signatures.
We have these orgs: [N0MoreSecr3ts]
We have these users: []
We have these repos: [wraith-test]
Gathering github organizations...
Added org N0MoreSecr3ts
Threads for repository gathering: 1
 Retrieved repository N0MoreSecr3ts/wraith-test from org N0MoreSecr3ts
Threads for repository analysis: 1
Analyzing 1 repository...
[THREAD #0] Requesting new repository to analyze...
[THREAD #0][https://github.com/N0MoreSecr3ts/wraith-test.git] Cloning repository...
[THREAD #0][https://github.com/N0MoreSecr3ts/wraith-test.git] Cloned repository to: /var/folders/kl/ywsfh4fj0pn3cptvz3w7dygw_gvl5t/T/wraith433968911
[THREAD #0][https://github.com/N0MoreSecr3ts/wraith-test.git] Number of commits: 1
[THREAD #0][https://github.com/N0MoreSecr3ts/wraith-test.git] Analyzing commit: 9e6ccd81ce0f56968413095d39c1c166fa147441
[THREAD #0][https://github.com/N0MoreSecr3ts/wraith-test.git] 0 changes in 9e6ccd81ce0f56968413095d39c1c166fa147441
[THREAD #0] Requesting new repository to analyze...
[THREAD #0] No more tasks, marking WaitGroup as done

--------Results--------

-------Findings------
Total Findings......: 0

--------Files--------
Total Files.........: 0
Files Scanned.......: 0
Files Ignored.......: 0
Files Dirty.........: 0

---------SCM---------
Repos Found.........: 4
Repos Cloned........: 2
Repos Scanned.......: 1
Commits Total.......: 1
Commits Scanned.....: 1
Commits Dirty.......: 0

-------General-------
Wraith Version......: 0.0.7
Signatures Version..: 0.0.1
Elapsed Time........: 1.42721376s

Any idea why this is not being analysed?

On top of that, there is a problem with the update signature process. It downloads a file, default.yaml, but the tool reads the rules from default.yml. I have copied and pasted the rules between files but the update process should fill the yml file

Thanks

**Comment by mattyjones** [comment]
@javixeneize Thanks for this, I will poke at it as soon as I can. Can you paste the command or config you used please.

Thanks!

**Comment by javixeneize** [comment]
Hi

just the default config with my GitHub token and running wraith scanGithub

**Comment by javixeneize** [comment]
this is the config file i have, just in case you need it:

---
commit-depth: 1
debug: true
github-api-token: [redacted]
github-orgs:
 - N0MoreSecr3ts
github-repos:
# - wraith
  - wraith-test
github-users:
  - N0MoreSecr3ts
gitlab-api-token: <token>
gitlab-targets:
  - 5034914
  - mattyjones
scan-forks: false
ignore-extension:
  - .html
  - .css
  - .log
ignore-path:
  - static/
  - docs/
in-mem-clone: false
local-paths:
  - ../wraith-signatures
match-level: 3
num-threads: 0
local-repos:
  - ../wraith-signatures
  - ../wraith
signature-file: ~/.wraith/signatures/default.yml
silent: false

**Comment by mattyjones** [comment]
@javixeneize Can you paste the code in
```
code brackets
```

as the yaml format so the formatting gets picked up. Doing this will make the config file much easier to read and troubleshoot.
Three backticks **\`\`\`yaml** and then code pasted below and then a newline and **\`\`\`** on the next line by itself.

Also the specific command such as `wraith scanGithubRepo foo` or whatever yours was.

Thanks!

**Comment by javixeneize** [comment]
I found the issue. It’s the value of commit depth. I increased it to 4 and now it works. Looks like hhe last commit doesn’t have anything to scan 
Maybe for testing the tool it would be good to do a full commit in the test repo

thanks. Apart from that, I like the tool. It’s useful. Can it also be used as a pre-commit tool (web hook)?

thanks

**Comment by mattyjones** [comment]
Yes it can look at the example hooks. All a git hook is, is a shell script. Just call wraith and point it as the local dir orpath you want to scan.

**Comment by circleous** [comment]
@javixeneize  in case you still missed where the bug is, in commit bf5f3ee1188271007ed1edd72b6978cda6adb1bd, match-level is updated to confidence-level. So, you might want to pull the newer wraith-signatures. I've created pull request for that (https://github.com/N0MoreSecr3ts/wraith-signatures/pull/2) and it's already merged into master.
