### ISSUE TITLE
Web Server not working?

### ISSUE THREAD

**Issue by Regala** [N0MoreSecr3ts/wraith#113]
Hi folks! Thanks for making this project alive. The last additions to be able to pass arguments in the command line makes it awesome.

Regarding the web server output - it appears to be broken? Just wanted to confirm:
![image](https://user-images.githubusercontent.com/1380527/121149697-cb55fa80-c83a-11eb-92c4-17f851349e6d.png)

Thanks! 💚

**Comment by mattyjones** [comment]
Yes, the threading breaks it. I made the call that performance was more important than the web interface, so I broke it and just haven't gotten to fixing it yet. More pressing bugs and functionality
