### ISSUE TITLE
Misconception on In-memory clone

### ISSUE THREAD

**Issue by circleous** [N0MoreSecr3ts/wraith#116]
In [github.go](https://github.com/N0MoreSecr3ts/wraith/blob/ecd2b954ccb795599bb1dc9f64940db4ed188762/core/github.go#L41-L47), 
```go
	if !*cloneConfig.InMemClone {
		dir, err = ioutil.TempDir("", "wraith")
		if err != nil {
			return nil, "", err
		}
		repository, err = git.PlainClone(dir, false, cloneOptions)
	} else {
		repository, err = git.Clone(memory.NewStorage(), nil, cloneOptions)
	}
```
On unix OSes, ioutil.TempDir() with en empty string as first argument usually create a directory in /tmp/. While it's not entirely wrong, usually /tmp/ is a tmpfs. tmpfs it self an in memory file system. While this is not a big issue on local pc, it's relatively eating up too many RAM resources on cloud servers or fargate tasks. I might be wrong on this one, so please CMIIW.

**Comment by mattyjones** [comment]
I am not sure, that functionality should not be available in the latest version. There are some known bugs, as you just hit, with some edge cases. I removed the flag in the latest release I believe till I could spend some time and dig deep into the functionality and usefulness. 

I completely agree it will eat up memory and cloning directly into memory for large jobs presents challenges. When threading you could be pulling down and searching multiple large repos, therefore killing memory. If this is going to be down the rate needs to be limited as well as ensuring that garbage is in fact being cleaned up and memory is freed when a repo is done being scanned.

@circleous

**Comment by mattyjones** [comment]
@circleous  Closing this out and moving it to a feature implementation ask. It needs to be rebuilt as a feature from scratch and research done on how to best do this if this is even done.
