### ISSUE TITLE
How to use 'commit-depth' in config.yml?

### ISSUE THREAD

**Issue by BrunoJu** [N0MoreSecr3ts/wraith#117]
What's the meaning of this configuration item in config.yml

> commit-depth = 1

**Comment by mattyjones** [comment]
@BrunoJu *commit-depth* refers to how deep into the commit history you want to scan. Ex. A depth of **100** means you want to scan the last 100 commits.

I am not sure why it was set to 1, my only thought was we were looking at doing a shallow clone of just the current working copy. The default is **-1** which implies that it is a full commit depth to the bottle of the rabbit hole. All other numbers imply a true commit depth so they would not make sensible defaults. Using **9999999999** as a default is also a mess so I went with **-1** as that is never going to be a commit-depth.
