### ISSUE TITLE
[RFC] Archicture Design Purposal

### ISSUE THREAD

**Issue by mattyjones** [N0MoreSecr3ts/wraith#41]
![Secrets Scanning.png](https://images.zenhubusercontent.com/5420711f7c6ccc6277a540ff/fc4b049b-d744-4aee-9edc-1b5a12fbd621)

The current thinking is to use [gRPC](https://grpc.io/about/) for communications between the major functions such as Output, Discovery and Detection, and each of their components. This will allow a new component such as a specific language parser or target such as Perforce, SVN, etc to be written in any supported language and versioned and managed independently of the main tool.

The configuration on the terminal side would be managed by [Viper](https://github.com/spf13/cobra), and the command interface by [Cobra](https://github.com/spf13/cobra). At some point, we may want a web interface for the input, especially if we go down the road of using this as a deployable service in a pipeline.

The output will remain terminal and web-based for the foreseeable future as both of these options have very strong use cases.

There is still a lot of planning and thinking that needs to be done from a mile high standpoint and then the implementation details are where the devil lays. Please feel free to comment on this thread as time goes on. At some point, this may be captured in a real document but for now threads make it easy to track comments and feedback.

@michenriksen @codeEmitter @plasticuproject @spekulatius I have tagged you as you either reach out directly to me or have a lot of contributions in the original project. None of this is set in stone but it moves the project leaps and bounds ahead for both blue and red team usage while still maintaining the ease of use for the core functionality.

**Comment by plasticuproject** [comment]
@mattyjones I would be interested in contributing to this project when it is a little more hashed out, further down the line. My Go skills are not that strong and it would be great to have a solid project to work on to improve them. So when it gets to the point where a sold design is worked out and there is a solid core code base I'd happily work on assigned modules or functionality.

**Comment by mattyjones** [comment]
@plasticuproject thanks. The reason I am looking at using gRPC is that the plugins can be written in any commonly used language such as Java, python, ruby, etc. You don't need to know Go. That said if you want to do things in Go that is great as well. There is still some behind the scenes stuff to be worked out with @codeEmitter and @michenriksen as they have large commits that would be really cool to have. Once I have a consensus that this is how we are going to move the project forward I am going to actually write everything up and then start hacking pieces out and then building in the existing functionality. There is a lot here for a part-time project but not so much that it is insurmountable. Go comes together fast and it fairly easy to pick up.

**Comment by mattyjones** [comment]
@plasticuproject The project has a fairly stable design at this point. Many of the major pieces are in place and there is a roadmap in the docs folder.
