### ISSUE TITLE
Error while installation with go get

### ISSUE THREAD

**Issue by ojasviashishchauhan** [N0MoreSecr3ts/wraith#62]
github.com/N0MoreSecr3ts/wraith@v0.0.0-20200825034140-f2174f602501: parsing go.mod:
        module declares its path as: wraith
                but was required as: github.com/N0MoreSecr3ts/wraith

**Comment by mattyjones** [comment]
I will look into this, honesty, I would clone the repo and `make build`

**Comment by mattyjones** [comment]
@ojaschauhan44 Can you share some more details such as what command you were using to build wraith, what operating are you building with and which one are you building for. Ex building windows/linux binaries on OSX or MacOS.

**Comment by melkorm** [comment]
👋  perhaps I can provide more information

```
➜  ~ go get -u "github.com/N0MoreSecr3ts/wraith"
package wraith/cmd: unrecognized import path "wraith/cmd": import path does not begin with hostname
```

probably module name is wrong, and should contain hostname (github) so it can be used properly by other modules and be installed by `go get`

**Comment by ghost** [comment]
x64:
```
$ docker run -it --rm golang:1-alpine
/go # uname -a
Linux f70495d3a65e 5.4.39-linuxkit #1 SMP TIMESTAMP x86_64 Linux
/go # apk add git
/go # go get -u "github.com/N0MoreSecr3ts/wraith"
package wraith/cmd: unrecognized import path "wraith/cmd": import path does not begin with hostname
```

arm64:
```
$ docker run -it --rm golang:1-alpine
/go # uname -a
Linux 88203a32a81a 5.4.0-1022-raspi #25-Ubuntu SMP PREEMPT TIMESTAMP aarch64 Linux
/go # apk add git
/go # go get -u "github.com/N0MoreSecr3ts/wraith"
package wraith/cmd: unrecognized import path "wraith/cmd": import path does not begin with hostname
```

**Comment by mattyjones** [comment]
Thanks for this, I think I am not adding the path correctly. Will fix this up and do a release in the next few days. Thanks for testing this for me.
@kairzha

**Comment by mattyjones** [comment]
![Screen Shot 2021-01-22 at 12.40.32 PM.png](https://app.gitkraken.com/api/glo/boards/5f31f99bcbb2fc0011226f33/attachments/600b0e3d177177001177bc22)

I am not seeing that from using your above command in the `src` directory.

**Comment by mattyjones** [comment]
I can't seem to replicate it with your notes @kairzha. If you are still hitting it following my above screenshot please let me and I will try and dig further into it.

Thanks.
