### ISSUE TITLE
not able to run scan commands

### ISSUE THREAD

**Issue by ojasviashishchauhan** [N0MoreSecr3ts/wraith#63]
![image](https://user-images.githubusercontent.com/24221890/91933794-5d0e6580-ed07-11ea-8539-20d013ddf994.png)

**Comment by mattyjones** [comment]
@ojaschauhan44 Can you post the command you used and the version you are running. The mos likely cause is that you didn't give it any repos, users, or other targets so the thread count gets out of whack, and the counter is 0/-1.

**Comment by ojasviashishchauhan** [comment]
oh, i was using an older release. that caused the issues
