### ISSUE TITLE
CSV and JSON output

### ISSUE THREAD

**Issue by mattyjones** [N0MoreSecr3ts/wraith#64]
@funkwhatyouheard

This function should work. You may still need to add the flags to the command line. The bits should still be in the season struct as well. I don't remember. I wrote this for another version and just didn't get around to re-implementing it here. Like I said it should work but at the least it is a starting point.

There are bound to be some variables that don't line up of fields that need to be changed or eliminated. I wrote this over 2 years ago. Any questions feel free to ping me here or we can talk it out through slack.

```go
// summaryOutput will spit out the results of the hunt along with performance data
func summaryOutput(sess *Session) {

	// alpha sort the findings to make the results idempotent
	if len(sess.Findings) > 0 {
		sort.Slice(sess.Findings, func(i, j int) bool {
			return sess.Findings[i].SecretID < hunt.Findings[j].SecretID
		})
	}

	if sess.JSONOutput {
		if len(sess.Findings) > 0 {
			b, err := json.MarshalIndent(sess.Findings, "", "    ")
			if err != nil {
				fmt.Println(err)
				return
			}
			c := string(b)
			if c == "null" {
				fmt.Println("{}")
			} else {
				fmt.Println(c)
			}
		} else {
			fmt.Println("{}")
		}
	}

	if sess.CSVOutput {
		w := csv.NewWriter(os.Stdout)
		defer w.Flush()
		header := []string{
			"FilePath",
			"Line Number",
			"Action",
			"Description",
			"RuleId",
			"Finding List",
			"Repo Owner",
			"Repo Name",
			"Commit Hash",
			"Commit Message",
			"Commit Author",
			"File URL",
			"Secret ID",
			"Grover Version",
			"Rules Version",
		}
		w.Write(header)

		for _, v := range sess.Findings {
			line := []string{
				v.FilePath,
				v.LineNumber,
				v.Action,
				v.Description,
				v.Ruleid,
				v.Comment,
				v.RepositoryOwner,
				v.RepositoryName,
				v.CommitHash,
				v.CommitMessage,
				v.CommitAuthor,
				v.FileURL,
				v.SecretID,
				v.GroverVersion,
				v.RulesVersion,
			}
			w.Write(line)
		}
	}
```

**Comment by funkwhatyouheard** [comment]
Thansk! CSV portion looks similar to what I had but I wanted to try it with reflection so if findings struct ever changes, no one will have to run around updating the list of fields. After some head banging, think I got something decent using reflection.  Hoping to get a PR in today.

**Comment by mattyjones** [comment]
Implemented

**Comment by funkwhatyouheard** [comment]
Might be missing something, but not seeing this implemented in the current version

**Comment by funkwhatyouheard** [comment]
@mattyjones

**Comment by mattyjones** [comment]
@funkwhatyouheard This is in the develop branch, not yet in master.

**Comment by funkwhatyouheard** [comment]
derp, right you are. Sorry about that!
