### ISSUE TITLE
All gathering and analysis should use Go routines

### ISSUE THREAD

**Issue by mattyjones** [N0MoreSecr3ts/wraith#68]
Gathering Github orgs and repos is not using go routines or contexts. The analysis, finding the secrets, is using go routines. Using go routines for gathering repos would drastically increase performance.

The simpliest way to do this would be to look at the [AnalyzeRepositories](https://github.com/N0MoreSecr3ts/wraith/blob/develop/core/analysis.go#L73) function as an example of how it could be done. Not all gathering functions need Go routines, it may only make to do it to specific ones.

When guaging the performanc, you can look at the total elapsed time of the scan at the bottom of the summery when a scan is complete.

**Comment by Gituser143** [comment]
Hi @mattyjones! Can I take this up?

**Comment by mattyjones** [comment]
@Gituser143 Sure, that would be great! If I can help in any way, please let me know.

**Comment by Gituser143** [comment]
@mattyjones Just to confirm, I'm supposed to be working on `GetRepositoriesFromOwner()` and `GetOrganizationMembers()` in `core/github.go` and `core/gitlab.go` right? Please let me know if I'm missing any functions.

**Comment by Gituser143** [comment]
@mattyjones made a PR for the same. #77 

Currently implemented and tested for functions only in `core/github.go`. Please do let me know if this fine and if I should implement routines for `core/gitlab.go` too.

**Comment by Gituser143** [comment]
@mattyjones Please take a look at #78 . I've implemented go routines for gitlab gathering too!
