### ISSUE TITLE
The gather org members flag is not working correctly

### ISSUE THREAD

**Issue by mattyjones** [N0MoreSecr3ts/wraith#73]
When you set the gather-org-members flag to true, the member's repos are not also pulled in to the scan.

**Comment by GabrielRato** [comment]
Hi @mattyjones I could take a look on that.

**Comment by mattyjones** [comment]
@GabrielRato Sure, that would be great. If I help in anyway please let me know!

**Comment by mattyjones** [comment]
This is fixed
