### ISSUE TITLE
support for multiple github access tokens to avoid rate limits

### ISSUE THREAD

**Issue by ajaykulal** [N0MoreSecr3ts/wraith#74]
Please add support for multiple github access tokens to avoid rate limits

**Comment by mattyjones** [comment]
@ajaykulal 
How would this avoid rate limits. Even you cycle through tokens, you will still hit network limits. Honestly, using this tool to the extent it can be used will present itself as a DOS attack long before you hit limits.

I am not against this thought, just not sure it is worth the effort to solve as we will simply hit another wall.
