### ISSUE TITLE
Error scanning GHE 

### ISSUE THREAD

**Issue by pradeepkusingh** [N0MoreSecr3ts/wraith#75]
Tried to scan GHE using PULL requesr 61 in develop branch.. getting below errors 

Failed to retrieve repositories from ORG NAME

some repos name

I am in the first for loop
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc000442020, 0xffffffffffffffff)
        /usr/local/go/src/sync/waitgroup.go:74 +0x147
wraith/core.AnalyzeRepositories(0xc0003a6840)
        /Users/psingh200/go/src/wraith/core/analysis.go:93 +0xea

**Comment by pradeepkusingh** [comment]
somehow I fixed the above issue and when I moved forward noticed SSH closing error unknown hosts, but my other git tools are working with ssh setup.

 ssh: handshake failed: knownhosts: key mismatch

**Comment by mattyjones** [comment]
So the wait group error is generally because there are no targets for it to scan.

I am confused by how you fixed it. The tool is solely https, it does not use SSH keys for any communication. All of it is via token auth.

I would say the two are unrelated, the issue seems to be most likely solved by setting an org/repo/user that Ould be reached via the given token and was not restricted or blocked by a 404 caused by a permissions/access issue.

@pradeepkusingh

**Comment by pradeepkusingh** [comment]
I am passing the org value and GHE token , not trying to use SSH. This toke has all access to ORG as I used google github api and can access all.

wraith v0.0.5 started at 2020-10-15T05:54:27-06:00
Loaded 0 signatures.
Web interface available at http://127.0.0.1:9393
Gathering github organizations...
I am here
Threads for repository gathering: 1
I am in the first for loop
org name (loginVal):  test
I am after we gather the org repos
 Failed to retrieve repositories from test: GET https://github.xxxxxx.com/api/v3/orgs/test/repos?page=2&type=sources: 500  []

**Comment by pradeepkusingh** [comment]
here are the argument 👍 
 go run main.go  scanGithubEnterprise --github-enterprise-api-token xxxxxxx   --github-enterprise-orgs test  --github-enterprise-url https://github.xxxxxxxx.com/api/v3 --debug true --num-threads 10

**Comment by pradeepkusingh** [comment]
Error cloning repository : ssh: handshake failed: knownhosts: key mismatch
Even I am surprised why it is doing SSH key handshake?

@mattyjones

**Comment by mattyjones** [comment]
@pradeepkusingh I will poke at this but you are not using signatures, the number loaded is 0. You need to pull the signatures down from the other repo and either pu them in the default location or you need to specify their path.

**Comment by pradeepkusingh** [comment]
Thanks @mattyjones  but it shows names of my all repose while run scan. Do you see anything wrong with the above commands? I just pasted below as well,  my requirement is scan all repos in an org.

go run main.go scanGithubEnterprise --github-enterprise-api-token xxxxxxx --github-enterprise-orgs test --github-enterprise-url https://github.xxxxxxxx.com/api/v3 --debug true --num-threads 10
