### ISSUE TITLE
Cannot run the lattest version ?

### ISSUE THREAD

**Issue by opatrecsec** [N0MoreSecr3ts/wraith#79]
Hi, 
Just finished setting up my Go environment + wraith 

When launching the script, I have this following output:
"Wraith **v0.0.1** started at 2020-10-16T11:52:34+02:00"

i don't see why its still v0.0.1 while i downloaded the latest release (v0.0.5)

Furthermore, I can't use a wraith config file to pass the flags to the script ; I'm forced to write them in the CLI

Are these 2 events related?

Thanks

**Comment by mattyjones** [comment]
@opatrecsec I am fixing the version now. The other issue I am not sure about and will test it out tonight.

**Comment by mattyjones** [comment]
this is fixed in master @opatrecsec
