### ISSUE TITLE
Error cloning repository

### ISSUE THREAD

**Issue by AhmedBakrDA** [N0MoreSecr3ts/wraith#81]
Hi all,
the tool was working fine, but now every time i run it , i get the following error:
Error cloning repository org/repo: read tcp 192.168.1.7:39334->140.82.121.3:443: read: connection reset by peer
any help?

**Comment by AhmedBakrDA** [comment]
this happens with all repos and iam not getting any result,

**Comment by mattyjones** [comment]
@sasokyleader Can you clone other repos from other projects. That sounds like a GitHub issue that shouldn't be specific to these repos. I cloned it just fine, via SSH w/o a key.

**Comment by AhmedBakrDA** [comment]
@mattyjones 
the error keep showing every time i try to use the tool with any repo,
I tried it with old projects that i cloned before and the same problem.

**Comment by AhmedBakrDA** [comment]
had you found any solution for this?
