### ISSUE TITLE
Error / Unable to scan 

### ISSUE THREAD

**Issue by codeanddie** [N0MoreSecr3ts/wraith#86]
How do I get past this error?

Here is the debug info:

wraith v0.0.5 started at 2020-12-11T00:37:30-07:00
Loaded 61 signatures.
Web interface available at http://127.0.0.1:9393
Gathering github organizations...
I am here
Threads for repository gathering: 1
I am in the first for loop                                                                                                                                            
org name (loginVal):  hackycorp
I am after we gather the org repos
 Retrieved repository: hackycorp/test1
 Retrieved repository: hackycorp/repo3                                                                                                                                
 Retrieved repository: hackycorp/repo4                                                                                                                                
 Retrieved repository: hackycorp/repo7                                                                                                                                
 Retrieved repository: hackycorp/repo9                                                                                                                                
 Retrieved repository: hackycorp/repo0a                                                                                                                               
I am in the first for loop                                                                                                                                            
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc00037e950, 0xffffffffffffffff)
        /usr/lib/go-1.15/src/sync/waitgroup.go:74 +0x147
wraith/core.AnalyzeRepositories(0xc00015e840)
        /home/c7d8fjsakjsd85/Downloads/wraith-master/core/analysis.go:93 +0xea
wraith/cmd.glob..func1(0x166e980, 0xc0001185a0, 0x0, 0x6)
        /home/c7d8fjsakjsd85/Downloads/wraith-master/cmd/scanGithub.go:61 +0x6c5
github.com/spf13/cobra.(*Command).execute(0x166e980, 0xc0001184e0, 0x6, 0x6, 0x166e980, 0xc0001184e0)
        /home/c7d8fjsakjsd85/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x166e6e0, 0x4473aa, 0x15c9780, 0xc000000180)
        /home/c7d8fjsakjsd85/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/c7d8fjsakjsd85/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
wraith/cmd.Execute()
        /home/c7d8fjsakjsd85/Downloads/wraith-master/cmd/root.go:22 +0x31
main.main()
        /home/c7d8fjsakjsd85/Downloads/wraith-master/main.go:27 +0x25
exit status 2

**Comment by mattyjones** [comment]
This is fixed in master @niraj-codes
