### ISSUE TITLE
Error while running GitHub Scan

### ISSUE THREAD

**Issue by osama-set** [N0MoreSecr3ts/wraith#90]
I am getting this error when I am running Github Scan:

```
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /stats                    --> wraith/core.NewRouter.func1 (3 handlers)
[GIN-debug] GET    /findings                 --> wraith/core.NewRouter.func2 (3 handlers)
[GIN-debug] GET    /targets                  --> wraith/core.NewRouter.func3 (3 handlers)
[GIN-debug] GET    /repositories             --> wraith/core.NewRouter.func4 (3 handlers)
[GIN-debug] GET    /files/:owner/:repo/:commit/*path --> wraith/core.fetchFile (3 handlers)
[GIN-debug] Listening and serving HTTP on 127.0.0.1:9393

____    __    ____ .______          ___       __  .___________. __    __
\   \  /  \  /   / |   _  \        /   \     |  | |           ||  |  |  |
 \   \/    \/   /  |  |_)  |      /  ^  \    |  | `---|  |----`|  |__|  |
  \            /   |      /      /  /_\  \   |  |     |  |     |   __   |
   \    /\    /    |  |\  \----./  _____  \  |  |     |  |     |  |  |  |
    \__/  \__/     | _| `._____/__/     \__\ |__|     |__|     |__|  |__|



wraith v0.0.6 started at 2021-01-25T13:59:03+05:00
Loaded 0 signatures.
Web interface available at http://127.0.0.1:9393
We have these orgs: [a]
We have these users: []
We have these repos: []
Gathering github organizations...

Retrieved repository a/objectivec-quickstart-platform from org a
 Retrieved repository a/python-quickstart-platform from org a
 Retrieved repository a/kotlin from org a
 Retrieved repository a/graphql-a-subscriptions from org a
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc000245690, 0xffffffffffffffff)
        /usr/local/go/src/sync/waitgroup.go:74 +0x147
wraith/core.AnalyzeRepositories(0xc0000c9600)
        /home/humayl/go/src/wraith/core/analysis.go:96 +0xea
wraith/cmd.glob..func1(0x1654840, 0xc000081b30, 0x0, 0x5)
        /home/humayl/go/src/wraith/cmd/scanGithub.go:79 +0x7c8
github.com/spf13/cobra.(*Command).execute(0x1654840, 0xc000081ae0, 0x5, 0x5, 0x1654840, 0xc000081ae0)
        /home/humayl/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x16545a0, 0x44736a, 0x15b16c0, 0xc000000180)
        /home/humayl/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/humayl/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
wraith/cmd.Execute()
        /home/humayl/go/src/wraith/cmd/root.go:22 +0x31
main.main()
        /home/humayl/go/src/wraith/main.go:29 +0x25
```

**Comment by malinoismalware** [comment]
make sure you include _--num-threads_ in command line arguments, for some reason default number of threads set to -1 which causes the error

core/session.go line 57 has the -1 value

**Comment by osama-set** [comment]
@malinoismalware thanks this fixed the issue but i now that i am trying to use the config file i am getting error here is the screenshot of my config and the error that i am getting

<img width="845" alt="image" src="https://user-images.githubusercontent.com/74716056/106256057-a0301e80-623c-11eb-9aa0-d7e6db66e8b1.png">

**Comment by mattyjones** [comment]
@malinoismalware Thanks for clearing that up. I am trying to work through that piece. `-1` in the codebase means full bore, threads are calculated based on the number of repos, commit depth goes back to the beginning of time, etc. There is a bug where if only a single repo is given both the commit depth and number of threads will puke at times. Still trying to trace it through as I can only replicate it sometimes.

**Comment by mattyjones** [comment]
@osama-set Is the token scoped correctly. I have seen this several times, and generally, it is because either the user has not given the token the correct access rights or is trying to reach a repo/org they don't have access rights to. The simplest way is to test this is to create a God token with full rights and try again.

If it works you know the repo/org permissions are correct and it was the token cope. If it does not work then you need to look closer at the repo/org permissions assigned to the token user.

**Comment by mattyjones** [comment]
@malinoismalware @osama-set Looking closer at the debug output, thanks for that, it shows no sigs added, and no valid repo's and orgs. I am almost 100% sure looking at the output and tracing the code, the root problem was no orgs or repos. That is where the waitgroup is unhappy as it can't find targets to thread. Setting a specific thread count means it will not be dynamically set and will ignore the count of repos and orgs, in this case, `0`

Test it by doing a scan with no repos and orgs, that should give you the same error, just leave the lists empty. After that, test it by setting the count to 1 and still give it no repos or orgs, the problem should not happen. Loading no sigs should not give an error at all, it should just pass through, not finding anything.

Let me know the results if you can confirm mine I will dig in and through some code around the issue to keep it from panicking.
