### ISSUE TITLE
Wraith not reading configuration file/signatures correctly

### ISSUE THREAD

**Issue by william-vanschaik** [N0MoreSecr3ts/wraith#92]
I am running wraith compiled from source based on the instructions in the readme and using MacOS 11.1. Signatures have been cloned from the signature repo and store under ~/.wraith as per instructions. All code versions are the latest pulled down within the last few days. 

This loads zero signatures and does not load any of the configuration options. I can specify the configuration options I want via command line arguments and this does work correctly, however no signatures are loaded. This is the case even when specifically providing the signature file in the command line arguments.

I know the signature file is being read and validated. If i add something to break the yaml of the signature file it does show a corresponding error when loading into wraith, however the same file when valid default signatures still does not load any signatures. This makes me reasonably sure that the file and the permissions are correct and wraith is indeed reading from it, so I would expect the default signatures to be loaded, but this does not seem to be the case. 

Any idea what may be causing this issue? Thanks!

```
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /stats                    --> wraith/core.NewRouter.func1 (3 handlers)
[GIN-debug] GET    /findings                 --> wraith/core.NewRouter.func2 (3 handlers)
[GIN-debug] GET    /targets                  --> wraith/core.NewRouter.func3 (3 handlers)
[GIN-debug] GET    /repositories             --> wraith/core.NewRouter.func4 (3 handlers)
[GIN-debug] GET    /files/:owner/:repo/:commit/*path --> wraith/core.fetchFile (3 handlers)
[GIN-debug] Listening and serving HTTP on 127.0.0.1:9393

____    __    ____ .______          ___       __  .___________. __    __
\   \  /  \  /   / |   _  \        /   \     |  | |           ||  |  |  |
 \   \/    \/   /  |  |_)  |      /  ^  \    |  | `---|  |----`|  |__|  |
  \            /   |      /      /  /_\  \   |  |     |  |     |   __   |
   \    /\    /    |  |\  \----./  _____  \  |  |     |  |     |  |  |  |
    \__/  \__/     | _| `._____/__/     \__\ |__|     |__|     |__|  |__|



wraith v0.0.6 started at 2021-03-01T10:03:16-05:00
Loaded 0 signatures.
Web interface available at http://127.0.0.1:9393
```

**Comment by william-vanschaik** [comment]
A similar error occurs when compiled and run on a linux based docker container. Zero signatures are loaded, but the signature version is displayed at the end of the run indicating the file was read, although there are no results.

**Comment by Voske1985** [comment]
It seems like the confidence-level from the default rules is (parsed as) 0; while the default minimum confidence level is 3

try adding with the following to your config:
confidence-level: 0

**Comment by william-vanschaik** [comment]
@Voske1985 Thanks, that seemed to do the trick. Did I miss something in the documentation?

**Comment by Voske1985** [comment]
I don't think so. I figured it out by debugging the code and trying to figure out why it wasn't accepting the rules.
