### ISSUE TITLE
Allow alternate config file location.

### ISSUE THREAD

**Issue by flowchartsman** [N0MoreSecr3ts/wraith#94]
Restricting configuration to exist in `$HOME` limits use of this tool in an automated way. Please consider adding a root-level flag to specify the configuration location.

**Comment by mattyjones** [comment]
@flowchartsman I thought that was already in there, looks like I was mistaken. This should be fairly simple, by adding a flag to each command and then setting it [here](https://github.com/N0MoreSecr3ts/wraith/blob/8933ca804f74bd6b364ee9eb22b0cfab101fb1ad/core/session.go#L157).
There should also be a default entry as well set to the original location to ensure we have a fallback.

Is this something you would like to PR? Happy to take PR's.

[This](https://github.com/spf13/viper#reading-config-files) could be helpful

**Comment by mattyjones** [comment]
@flowchartsman I am poking at this now, working through doing it cleanly so that it is global and can be a single file for all subcommands, following the existing pattern. There is a feature branch but the code is not yet stable.

**Comment by mattyjones** [comment]
@flowchartsman This has now been implemented.
