### ISSUE TITLE
Failed to load signatures

### ISSUE THREAD

**Issue by zeem71** [N0MoreSecr3ts/wraith#98]
While running wraith I am getting 

> Failed to load signatures file default.yaml: yaml: line 92: mapping values are not allowed in this context

However Yaml file is properly indented and formatted

**Comment by mattyjones** [comment]
@zeem71 I can poke at this if you post a sanitized version of your yaml. I use http://www.yamllint.com/ and have never had an issue. With that said you may also want to look at the yaml requirements for viper, which is used to read in the yaml and parse it.

It could be simply I have not created a data structure that can handle this.
