### ISSUE TITLE
Signature file path not found

### ISSUE THREAD

**Issue by nicholasgpuig** [N0MoreSecr3ts/wraith#99]
When I start wraith in with the debug flag, it shows
`Path does not exist: stat $HOME/.wraith/signatures/default.yaml: no such file or directory`
I have the default.yaml file in the signatures folder in the wraith master directory.
No matter which directory I run it in, this debug message always appears. I have the wraith directory in my path too.

**Comment by mattyjones** [comment]
@Skyawesome73 What version are you running?

It may be that it is still looking for the `.yml` extension and not the 4 letter version. If you give me the version number I can spin it up and check that path. You can also try pulling the latest version and seeing if that error presents itself. If it does please go to the directory where the signatures should be and give me the full path so I can look into it. 

It could be the path is not getting expanded correctly for some reason or the code may have a bug in the function used to pull in user-specific flags.

**Comment by nicholasgpuig** [comment]
I am currently running the latest version because I just uninstalled and reinstalled wraith right now, and the same error message is present. The signatures path is "$HOME/wraith/signatures/default.yaml".

After using git clone to install wraith, the error message is gone now, but now it tells me that my GitHub api key is invalid. I have two api keys, a god one and another one, and both return the same message. They both still work, so I'm convinced it is not the key's fault. I put the key into the config file in the main wraith directory, and it seems like it's still not properly reading the config file. 

Edit: I'm able to get wraith running by using the --github-api-token flag, but now I am getting the same error message as in issue #86. I have the latest version too.

**Comment by mattyjones** [comment]
@Skyawesome73 Your path above says  _$HOME/wraith/signatures/default.yaml_ the config directory is actually **.wraith** you are missing the **.** that makes it a hidden directory.

See if that clears it up. If not please reopen this and I will keep trucking through for anything else it could be.
